# syntax=docker/dockerfile:1
FROM golang:1.23.3 AS deps
WORKDIR /app
RUN go install github.com/mitranim/gow@latest

FROM deps AS build
COPY go.mod go.sum main.go ./
COPY internal ./internal
RUN \
  --mount=type=cache,target=/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go mod tidy && \
  go mod download && \
  go build \
    -ldflags="-linkmode external -extldflags -static" \
    -tags netgo \
    -o app

FROM scratch AS finall
COPY --from=build /app/app /app
EXPOSE 8080
CMD ["./app", "run"]
