[tools]
pre-commit      = 'latest'
python          = '3.12'
go              = '1.23.3'
golangci-lint   = 'latest'
'go:golang.org/x/tools/cmd/goimports'                     = 'latest'
'go:github.com/golangci/golangci-lint/cmd/golangci-lint'  = 'latest'
'go:github.com/fzipp/gocyclo/cmd/gocyclo'                 = 'latest'
'go:github.com/go-critic/go-critic/cmd/gocritic'          = 'latest'
'go:github.com/mitranim/gow'                              = 'latest'
'go:github.com/BurntSushi/toml/cmd/tomlv'                 = 'latest'

[settings]
not_found_auto_install = true
experimental = true
