# https://stackoverflow.com/questions/67498836/docker-chown-changing-ownership-of-data-db-operation-not-permitted

services:
  app-golang:
    build:
      context: golang
    container_name: app-golang
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - grafana

  app-dotnet:
    build:
      context: dotnet
    container_name: app-dotnet
    environment:
      - OTLP_HOSTNAME=opentelemetry
    ports:
      - 8081:8080

# ---

  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password123
      - MONGO_INITDB_DATABASE=Data
    ports:
      - 27017
    volumes:
      - mongodb-data:/data/db
      - ./docker-compose/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    volumes:
      - ./docker-compose/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command: [ "--config.file=/etc/prometheus/prometheus.yaml" ]
    depends_on:
      - grafana
    volumes:
      - ./docker-compose/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    ports:
      - 3200 # tempo http
      - 3201 # tempo grpc
      - 4317 # otlp grpc
      - 4318 # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      - grafana
    volumes:
      - ./docker-compose/tempo/tempo.yaml:/etc/tempo.yaml

  loki:
    image: grafana/loki:3.1.2
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100 # loki http
      - 9095 # loki grpc
    command: [ "-config.file=/etc/loki.yaml" ]
    depends_on:
      - grafana
    volumes:
      - ./docker-compose/loki/loki.yaml:/etc/loki.yaml

# ---

  opentelemetry:
    image: otel/opentelemetry-collector:0.112.0
    container_name: opentelemetry
    restart: unless-stopped
    ports:
      - 4317 # otlp grpc
      - 4318 # otlp http
    command: --config=/etc/opentelemetry/config.yaml
    depends_on:
      - grafana
    volumes:
      - ./docker-compose/opentelemetry/config.yaml:/etc/opentelemetry/config.yaml

volumes:
  mongodb-data:
