# https://stackoverflow.com/questions/67498836/docker-chown-changing-ownership-of-data-db-operation-not-permitted

services:
  app-golang:
    build:
      context: golang
    container_name: app-golang
    ports:
      - 8080:8080

  app-dotnet:
    build:
      context: dotnet
    container_name: app-dotnet
    ports:
      - 8081:8080

# ---

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password123
      - MONGO_INITDB_DATABASE=Data
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./docker-compose/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    volumes:
      - ./docker-compose/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command: [ "--config.file=/etc/prometheus/prometheus.yaml" ]
    volumes:
      - ./docker-compose/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200 # tempo http
      # - 3201 # tempo grpc
      - 4317 # otlp grpc
      - 4318 # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker-compose/tempo/tempo.yaml:/etc/tempo.yaml

# ---

  opentelemetry:
    image: otel/opentelemetry-collector:latest
    container_name: opentelemetry
    restart: unless-stopped
    ports:
      - 4317 # otlp grpc
      - 4318 # otlp http
    command: --config=/etc/opentelemetry/config.yaml
    depends_on:
      - grafana
    volumes:
      - ./docker-compose/opentelemetry/config.yaml:/etc/opentelemetry/config.yaml

volumes:
  mongodb-data:
