receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

connectors:

exporters:
  otlp/1:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/2:
    endpoint: loki:9095
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/1]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/2]
