server:
  http_listen_port: 3200
  grpc_listen_port: 3201

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  processor:
    span_metrics:
    service_graphs:

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

# overrides:
#   metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
