name: "Reusable"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  assign:
    name: "Assign"
    uses: Inetum-Poland/.github/.github/workflows/assign_tag.yml@main
    with:
      bump_default_level: patch
      bump_latest: true
